packages:
  - apps/*
  - packages/*

catalog:
  react: 19.2.1
  react-dom: 19.2.1
  next: 16.0.7
  tailwindcss: 4.1.16
  '@tailwindcss/postcss': 4.1.16
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-dialog': 1.1.15
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  lucide-react: 0.475.0
  tailwind-merge: 3.3.1
  tw-animate-css: 1.4.0
  '@biomejs/biome': 2.3.3
  '@turbo/gen': 2.6.0
  typescript: 5.9.3
  '@types/node': 20.19.24
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  supabase: 2.54.11
  knip: 5.67.1
  cspell: 9.4.0
  drizzle-orm: 0.44.7
  drizzle-kit: 0.31.0
  postgres: 3.4.5
  '@harusame0616/result': 0.1.3
  '@hookform/resolvers': 5.2.2
  react-hook-form: 7.66.0
  valibot: 1.1.0
  '@supabase/ssr': 0.7.0
  '@supabase/supabase-js': 2.79.0
  vitest: 4.0.8
  '@vitest/browser-playwright': 4.0.8
  '@vitest/ui': 4.0.8
  '@playwright/test': 1.57.0
  vitest-browser-react: 0.0.3
  '@vitejs/plugin-react': 5.1.0
  pino: 9.7.0
  pino-pretty: 13.1.2
  tsx: 4.20.6
  uuid: 13.0.0
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-select': 2.2.6
  cmdk: 1.1.1
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-collapsible': 1.1.12
  embla-carousel-react: 8.6.0
  vaul: 1.1.2
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@modelcontextprotocol/sdk': 1.24.3
  mcp-handler: 1.0.4
  zod: 4.1.13

catalogMode: strict

onlyBuiltDependencies:
  - supabase
  - sharp
  - unrs-resolver
