packages:
  - apps/*
  - packages/*

catalog:
  react: 19.2.1
  react-dom: 19.2.1
  next: 16.0.7
  tailwindcss: 4.1.17
  '@tailwindcss/postcss': 4.1.17
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-switch': 1.2.6
  '@radix-ui/react-dialog': 1.1.15
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  lucide-react: 0.556.0
  tailwind-merge: 3.4.0
  tw-animate-css: 1.4.0
  '@biomejs/biome': 2.3.8
  '@turbo/gen': 2.6.3
  typescript: 5.9.3
  '@types/node': 24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  supabase: 2.65.6
  knip: 5.71.0
  cspell: 9.4.0
  drizzle-orm: 0.45.0
  drizzle-kit: 0.31.8
  postgres: 3.4.7
  '@harusame0616/result': 0.1.3
  '@hookform/resolvers': 5.2.2
  react-hook-form: 7.66.0
  valibot: 1.1.0
  '@supabase/ssr': 0.8.0
  '@supabase/supabase-js': 2.86.2
  vitest: 4.0.15
  '@vitest/browser-playwright': 4.0.15
  '@vitest/ui': 4.0.15
  '@playwright/test': 1.57.0
  vitest-browser-react: 2.0.2
  '@vitejs/plugin-react': 5.1.1
  pino: 9.7.0
  pino-pretty: 13.1.2
  tsx: 4.21.0
  uuid: 13.0.0
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-select': 2.2.6
  cmdk: 1.1.1
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-collapsible': 1.1.12
  embla-carousel-react: 8.6.0
  vaul: 1.1.2
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-dropdown-menu': 2.1.16

catalogMode: strict

onlyBuiltDependencies:
  - supabase
  - sharp
  - unrs-resolver
