packages:
  - apps/*
  - packages/*

catalog:
  react: 19.2.0
  react-dom: 19.2.0
  next: 16.0.1
  tailwindcss: 4.1.16
  '@tailwindcss/postcss': 4.1.16
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-label': 2.1.8
  '@radix-ui/react-switch': 1.2.6
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  lucide-react: 0.475.0
  next-themes: 0.4.6
  tailwind-merge: 3.3.1
  tw-animate-css: 1.4.0
  '@biomejs/biome': 2.3.3
  '@turbo/gen': 2.6.0
  typescript: 5.9.3
  '@types/node': 20.19.24
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  supabase: 2.54.11
  knip: 5.67.1
  drizzle-orm: 0.44.7
  drizzle-kit: 0.31.0
  postgres: 3.4.5
  '@harusame0616/result': 0.1.2
  '@hookform/resolvers': 5.2.2
  react-hook-form: 7.66.0
  valibot: 1.1.0
  '@supabase/ssr': 0.7.0
  '@supabase/supabase-js': 2.79.0
  vitest: 4.0.8
  '@testing-library/react': 16.3.0
  '@testing-library/jest-dom': 6.9.1
  '@testing-library/user-event': 14.6.1
  '@vitejs/plugin-react': 5.1.0
  '@vitest/ui': 4.0.8
  '@vitest/browser': 4.0.8
  '@vitest/browser-playwright': 4.0.8
  '@playwright/test': 1.56.1
  playwright: 1.56.1
  jsdom: 27.1.0

catalogMode: strict

onlyBuiltDependencies:
  - supabase
  - sharp
  - unrs-resolver
